data:
  metadata: data/annotations/metadata.csv
  tracings: data/annotations/tracings.csv
  raw: data/raw
  processed: data/processed
  echonet: data/echonet

wandb:
  datasets:
    images-masks: 'ernestoserize-constructor-university/echonet-dl/images-masks:v0'
  models:
    unet: 'ernestoserize-constructor-university/echonet-dl/unet:v0'